"""Database creation

Revision ID: b9c6ba818166
Revises: 
Create Date: 2024-03-13 22:41:31.291354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c6ba818166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('date', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_text',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_doc', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id_doc'], ['document.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents_text')
    op.drop_table('document')
    # ### end Alembic commands ###
