"""Second migration

Revision ID: dea35c46fc35
Revises: b9c6ba818166
Create Date: 2024-03-18 11:18:47.788472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea35c46fc35'
down_revision: Union[str, None] = 'b9c6ba818166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents_text', ['id_doc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents_text', type_='unique')
    # ### end Alembic commands ###
